# ARDUINO_DIR = /usr/share/arduino# ARDMK_DIR = /usr# AVT_TOOLS_DIR = /usrBOARD_TAG = atmega328ARDUINO_PORT = /dev/arduinottyARDUINO_LIBS =TARGET = sponginclude /usr/share/arduino/Arduino.mk
# apt-get install arduino-mk
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG = atmega328
ARDUINO_PORT = /dev/arduinotty
ARDUINO_LIBS =

# TARGET = temp-sensirion

include $(ARDUINO_DIR)/Arduino.mk
