[project]
name = "move-windows-to-mouse"
version = "0.1.0"
description = "Window movement utility with icon asset generation for Windows."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
dependencies = [
    "Pillow>=12.0.0",
    "CairoSVG>=2.9.0",
    "cairocffi>=1.7.1",
    "pycairo>=1.25.0",
    "pywin32>=311",
    "comtypes>=1.2.0",
    "pycaw>=20251023"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
