# ARDUINO_DIR = /usr/share/arduino
# ARDMK_DIR = /usr
# AVT_TOOLS_DIR = /usr

# apt-get install arduino-mk
ARDUINO_DIR = /usr/share/arduino
BOARD_TAG = atmega328
ARDUINO_PORT = /dev/ttyarduino
ARDUINO_LIBS =
AVRDUDE_OPTS = -v

TARGET = temp-sensors

include $(ARDUINO_DIR)/Arduino.mk
